server {
    listen 80;
    server_name localhost;

    # 所有的网页、刷新、跳转，全部归这里管
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html; # 只要不是真实文件，统统交给 Vue
    }

    # 所有的后端接口，统一归这里管
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_read_timeout 300s; # 给 SoVITS 留时间
        proxy_set_header Host $host;
        proxy_pass_request_headers on;
    }

    # 静态资源（不需要鉴权的）继续保持
    location /audio/ { 
        proxy_pass http://backend:8080; 
    }
    location /TTS_sound/ { 
        proxy_pass http://backend:8080; 
    }
    location /covers/ { 
        proxy_pass http://backend:8080; 
    }
    location /videos/ { 
        proxy_pass http://backend:8080; 
    }

}