services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jinju_project
    ports:
      - "3305:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 3. 缓存 (Redis)
  redis:
    image: redis:alpine
    restart: always

  # 4. 后端服务 (Node.js)
  backend:
    build: ./server
    container_name: node-backend
    depends_on:
      - db
      - redis
      # - sovits
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - ./server/videos:/app/server/videos
      - ./server/covers:/app/server/covers
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 5. 前端服务 (Vue)
  frontend:
      build: ./client
      container_name: jinju_project-frontend-1
      ports:
        - "80:80"
      depends_on:
        - backend
      restart: always